name: ðŸ”¨ Performance Test

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly
  workflow_dispatch:

jobs:
  perf-test:
    strategy:
      matrix:
        count: [50, 100, 150]
        flags: ['', '-race']
    runs-on: ubuntu-latest-16-cores
    if: github.repository == 'projectdiscovery/nuclei'
    env:
      LIST_FILE: "/tmp/targets-${{ matrix.count }}.txt"
      PROFILE_MEM: "/tmp/nuclei-perf-test-${{ matrix.count }}"
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1
      - run: make verify
      - name: Generate list
        run: for i in {1..${{ matrix.count }}}; do echo "https://scanme.sh/?_=${i}" >> "${LIST_FILE}"; done
      - run: go run ${{ matrix.flags }} . -l "${LIST_FILE}" -profile-mem="${PROFILE_MEM}"
        working-directory: cmd/nuclei/
      - run: ls -la /tmp | grep nuclei
      - uses: projectdiscovery/actions/flamegraph@v1
        id: flamegraph
        with:
          profile: "${{ env.PROFILE_MEM }}.prof"
          name: "nuclei-perf-test-${{ matrix.count }}"
        continue-on-error: true
      - if: ${{ steps.flamegraph.outputs.message == '' }}
        run: echo "::notice::${FLAMEGRAPH_URL}"
        env:
          FLAMEGRAPH_URL: ${{ steps.flamegraph.outputs.url }}