name: ðŸ›  Template Validate

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: 1.18

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v3
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Installing Nuclei
#        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          go install github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
      - name: Template Validation
        run: |
          nuclei -validate
          nuclei -validate -w ./workflows