name: ðŸ›  Template Validate

on:
  pull_request:
    paths:
      - '**.go'
  workflow_dispatch:

jobs:
  build:
    if: "! endsWith(github.actor, '[bot]')"
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v4
      - uses: projectdiscovery/actions/setup/go@v1
      - name: Template Validation
        run: |
          go run . -ut
          go run . -validate
          go run . -validate -w workflows
        working-directory: cmd/nuclei/